# Generated by Django 5.1 on 2024-08-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='door',
            old_name='published_date',
            new_name='date_post',
        ),
    ]
