# Generated by Django 5.1.1 on 2024-09-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="doors",
            field=models.ManyToManyField(blank=True, to="firstapp.door"),
        ),
        migrations.AlterField(
            model_name="room",
            name="furniture",
            field=models.ManyToManyField(blank=True, to="firstapp.furniture"),
        ),
        migrations.AlterField(
            model_name="room",
            name="windows",
            field=models.ManyToManyField(blank=True, to="firstapp.window"),
        ),
    ]
